[package]
name = "zek-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }