[package]
name = "zek-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
core-metrics = { path = "../../crates/core-metrics" }
tui = { path = "../../crates/tui" }